services:
  app:
    build:
      context: .
    networks:
      - node-net
    tty: true
    container_name: app
    # Await for db to be ready before starting the app, using dockerize
    command: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    depends_on:
      - db

  db:
    image: mysql:8.4.6
    command: ["--innodb-use-native-aio=0"]
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-net

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-net
    # entrypoint: dockerize -wait tcp://app:3000 -timeout 30s docker-entrypoint.sh
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-net:
    driver: bridge